# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 439ec42e6d99d4e7ba3561f95a4ea315d0994dd50e626303eae1b204aecfb2e09fbfcfa2010c9a4f850a76a544997f545cbcba9bd42e38aa2ef51d71b6716773

test:
  secret_key_base: fcf7ee5373288c6fcf6540be4c3e9aa3a305a8183ffab928a4e94655bfc02f21044d1d1e7b0ad071cd45fb5547620b8574e7dbc460b6486cdd90eb9d0ccf72c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
