# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.find_by(id: 1).update_attributes(is_leader: false)
User.find_by(id: 2).update_attributes(is_leader: false)
User.find_by(id: 3).update_attributes(is_leader: false)
User.find_by(id: 4).update_attributes(is_leader: false)
User.find_by(id: 5).update_attributes(is_leader: false)
User.find_by(id: 6).update_attributes(is_leader: false)
User.find_by(id: 7).update_attributes(is_leader: false)
User.find_by(id: 8).update_attributes(is_leader: false)
User.find_by(id: 9).update_attributes(is_leader: false)
User.find_by(id: 10).update_attributes(is_leader: false)
User.find_by(id: 11).update_attributes(is_leader: false)
User.find_by(id: 12).update_attributes(is_leader: false)
User.find_by(id: 13).update_attributes(is_leader: false)
User.find_by(id: 14).update_attributes(is_leader: false)
User.find_by(id: 15).update_attributes(is_leader: false)
User.find_by(id: 16).update_attributes(is_leader: false)
User.find_by(id: 17).update_attributes(is_leader: false)
User.find_by(id: 18).update_attributes(is_leader: false)
User.find_by(id: 19).update_attributes(is_leader: false)
User.find_by(id: 20).update_attributes(is_leader: false)
User.find_by(id: 21).update_attributes(is_leader: false)
User.find_by(id: 22).update_attributes(is_leader: false)
User.find_by(id: 23).update_attributes(is_leader: false)
User.find_by(id: 24).update_attributes(is_leader: false)
User.find_by(id: 25).update_attributes(is_leader: false)
User.find_by(id: 26).update_attributes(is_leader: false)
User.find_by(id: 27).update_attributes(is_leader: false)
User.find_by(id: 28).update_attributes(is_leader: false)
User.find_by(id: 29).update_attributes(is_leader: false)
User.find_by(id: 30).update_attributes(is_leader: false)
User.find_by(id: 31).update_attributes(is_leader: false)
User.find_by(id: 32).update_attributes(is_leader: false)
User.find_by(id: 33).update_attributes(is_leader: false)
User.find_by(id: 34).update_attributes(is_leader: false)
User.find_by(id: 35).update_attributes(is_leader: false)
User.find_by(id: 36).update_attributes(is_leader: false)