# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
ChurchGroup.create(name: 'Admin Team', leader: 'Administrator', region: 'UK')
ChurchGroup.create(name: 'Matthew', leader: 'Danniella Hart', region: 'London')
ChurchGroup.create(name: 'Jude', leader: 'Kent Njeru', region: 'Judea')
ChurchGroup.create(name: 'Ephesians', leader: 'Ben Blythsmith', region: 'London')
ChurchGroup.create(name: 'Luke', leader: 'Nana Amaning ', region: 'London')
ChurchGroup.create(name: 'Timothy', leader: 'Sarah Neizer', region: 'London')
ChurchGroup.create(name: 'James', leader: 'Esme Bentil ', region: 'Judea')
ChurchGroup.create(name: 'John', leader: 'Emmanuel Baiden', region: 'Judea')
ChurchGroup.create(name: 'Unclassified', leader: 'Jean Kabasomi', region: 'Judea')

User.create(email: 'bppflc1@gmail.com', name: "BPP University", elder: 'Aisha Abubaker', church_group_id: 5, password: 'bppf4321', password_confirmation: 'bppf4321')
User.create(email: 'southcollegesflc@gmail.com', name: "South London Colleges", elder: 'Akeem Davidson', church_group_id: 4, password: 'sout4321', password_confirmation: 'sout4321')
User.create(email: 'bloomsburyflc@gmail.com', name: "Bloomsbury - SOAS, IOE, UCL", elder: 'Beverly Jera', church_group_id: 2, password: 'bloo4321', password_confirmation: 'bloo4321')
User.create(email: 'sheffieldflc@gmail.com', name: "The University of Sheffield", elder: 'Bode Adekeye', church_group_id: 7, password: 'shef4321', password_confirmation: 'shef4321')
User.create(email: 'nottingamflc@gmail.com', name: "The University of Nottingham", elder: 'Charles Djbatey', church_group_id: 8, password: 'nott4321', password_confirmation: 'nott4321')
User.create(email: 'leedsflc@gmail.com', name: "The University of Leeds", elder: 'Danilo Andrade', church_group_id: 7, password: 'leed4321', password_confirmation: 'leed4321')
User.create(email: 'uelflc@gmail.com', name: "University of East London", elder: 'Danniella Craig', church_group_id: 2, password: 'uelf4321', password_confirmation: 'uelf4321')
User.create(email: 'northcollegesflc@gmail.com', name: "North London Colleges", elder: 'Dominique Manshadi', church_group_id: 4, password: 'nort4321', password_confirmation: 'nort4321')
User.create(email: 'westminsterflc@gmail.com', name: "Univeristy of Westminster", elder: 'Eden Lawer', church_group_id: 6, password: 'west4321', password_confirmation: 'west4321')
User.create(email: 'leicesterflc@gmail.com', name: "The Universirt of Leicester", elder: 'Emmanuel Baiden', church_group_id: 8, password: 'leic4321', password_confirmation: 'leic4321')
User.create(email: 'northamptonflc@gmail.com', name: "The Universirt of Northampton", elder: 'Esme Mantiziba', church_group_id: 7, password: 'nort4321', password_confirmation: 'nort4321')
User.create(email: 'coventryflc@gmail.com', name: "Coventry University", elder: 'Evelyn Osei', church_group_id: 3, password: 'cove4321', password_confirmation: 'cove4321')
User.create(email: 'southbankflc@gmail.com', name: "Univerisity of SouthBank", elder: 'Haggai Afriye', church_group_id: 4, password: 'sout4321', password_confirmation: 'sout4321')
User.create(email: 'portsmouthflc@gmail.com', name: "University of Portsmouth", elder: 'Jeffrey Osei-Bonsu', church_group_id: 7, password: 'port4321', password_confirmation: 'port4321')
User.create(email: 'queenmaryflc@gmail.com', name: "Queen Mary", elder: 'Jeremy Osei-Bonsu', church_group_id: 2, password: 'quee4321', password_confirmation: 'quee4321')
User.create(email: 'stmarystwickenhamflc@gmail.com', name: "St Mary's Twickenham", elder: 'Kemilya Mahadea', church_group_id: 4, password: 'stma4321', password_confirmation: 'stma4321')
User.create(email: 'birminghamflc@gmail.com', name: "Birmingham", elder: 'Kent Njeru', church_group_id: 3, password: 'birm4321', password_confirmation: 'birm4321')
User.create(email: 'loncityflc@gmail.com', name: "City Univeristy, London", elder: 'Marinda Yorke', church_group_id: 2, password: 'lonc4321', password_confirmation: 'lonc4321')
User.create(email: 'nottinghamtrentflc@gmail.com', name: "Nottingham Trent ", elder: 'Nanaamma Amaning', church_group_id: 8, password: 'nott4321', password_confirmation: 'nott4321')
User.create(email: 'miltonkeynesflc@gmail.com', name: "Milton Keynes", elder: 'Nanaefua Sagoe', church_group_id: 7, password: 'milt4321', password_confirmation: 'milt4321')
User.create(email: 'strandflc@gmail.com', name: "The Strand - LSE, KCL", elder: 'Natalie Commey', church_group_id: 6, password: 'stra4321', password_confirmation: 'stra4321')
User.create(email: 'bradfordflc@gmail.com', name: "University of Bradfird", elder: 'Neliya Ange', church_group_id: 8, password: 'brad4321', password_confirmation: 'brad4321')
User.create(email: 'bedfordflc@gmail.com', name: "University of Bedfordshire", elder: 'Richard Yorke', church_group_id: 9, password: 'bedf4321', password_confirmation: 'bedf4321')
User.create(email: 'middlesexflc@gmail.com', name: "Middlesex Univerisity", elder: 'Rochelle Owusu', church_group_id: 5, password: 'midd4321', password_confirmation: 'midd4321')
User.create(email: 'westlondonflc@gmail.com', name: "University of West London", elder: 'Sarah Neizer', church_group_id: 6, password: 'west4321', password_confirmation: 'west4321')
User.create(email: 'manchesterflc@gmail.com', name: "Universirt of Manchester", elder: 'Stacy Charway', church_group_id: 3, password: 'manc4321', password_confirmation: 'manc4321')
User.create(email: 'greenwichflc@gmail.com', name: "University of Greenwich", elder: 'Thomas Andrews', church_group_id: 5, password: 'gree4321', password_confirmation: 'gree4321')
User.create(email: 'plymouthflc@gmail.com', name: "Plymouth University", elder: 'Victory Poloamina', church_group_id: 9, password: 'plym4321', password_confirmation: 'plym4321')
User.create(email: 'londonmet@gmail.com', name: "London Metropolitan University", elder: 'Zhane Bennet', church_group_id: 5, password: 'lond4321', password_confirmation: 'lond4321')
User.create(email: 'aezeanaka@gmail.com', name: "Andy Ez", elder: 'Administrator', church_group_id: 1, password: 'aeze4321', password_confirmation: 'aeze4321')
User.create(email: 'jkabasomi@yahoo.co.uk', name: "Jean Kabasomi", elder: 'Administrator', church_group_id: 1, password: 'jkab4321', password_confirmation: 'jkab4321')
User.create(email: 'janehyde_@hotmail.com', name: "Jane Hyde", elder: 'Administrator', church_group_id: 1, password: 'jane4321', password_confirmation: 'jane4321')